-- Foundational migration: wallet_transactions table and credit_wallet RPC
-- This table and profiles.wallet_balance are required by later migrations (add_credit_loan, etc.)
-- Apply before 20250225000000_add_credit_loan.sql

-- 1. Add wallet_balance to profiles if not exists
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS wallet_balance BIGINT DEFAULT 0;

-- 2. Create wallet_transactions table
-- Note: UNIQUE (user_id, ref) - in Postgres, NULLs are distinct in unique constraints,
-- so multiple rows with (user_id, NULL) are allowed. RPCs always provide ref.
CREATE TABLE IF NOT EXISTS wallet_transactions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  amount_cents BIGINT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('deposit', 'purchase', 'sale', 'refund', 'adjustment')),
  currency TEXT NOT NULL DEFAULT 'usd',
  ref TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, ref)
);

-- 3. Create credit_wallet RPC (for deposits: Stripe, manual admin credits)
CREATE OR REPLACE FUNCTION credit_wallet(
  p_user_id UUID,
  p_amount_cents BIGINT,
  p_ref TEXT DEFAULT NULL,
  p_currency TEXT DEFAULT 'usd'
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF p_amount_cents <= 0 THEN
    RAISE EXCEPTION 'Amount must be positive';
  END IF;

  INSERT INTO wallet_transactions (user_id, amount_cents, type, currency, ref)
  VALUES (p_user_id, p_amount_cents, 'deposit', COALESCE(p_currency, 'usd'), COALESCE(p_ref, 'deposit_' || extract(epoch from now())::bigint));

  UPDATE profiles
  SET wallet_balance = COALESCE(wallet_balance, 0) + p_amount_cents
  WHERE id = p_user_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'User not found: %', p_user_id;
  END IF;
END;
$$;

-- 4. Enable RLS on wallet_transactions
ALTER TABLE wallet_transactions ENABLE ROW LEVEL SECURITY;

-- 5. RLS: Users can view their own transactions
DROP POLICY IF EXISTS "Users can view own wallet transactions" ON wallet_transactions;
CREATE POLICY "Users can view own wallet transactions"
  ON wallet_transactions FOR SELECT
  USING (auth.uid() = user_id);
