-- Weekly Leaderboard table per Oasis Internship schema
CREATE TABLE public.weekly_leaderboard (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  week_start TIMESTAMPTZ NOT NULL,
  week_end TIMESTAMPTZ NOT NULL,
  start_wallet_value BIGINT NOT NULL,
  start_portfolio_value BIGINT NOT NULL,
  start_account_value BIGINT NOT NULL,
  end_wallet_value BIGINT NOT NULL,
  end_portfolio_value BIGINT NOT NULL,
  end_account_value BIGINT NOT NULL,
  deposits_week BIGINT NOT NULL DEFAULT 0,
  weekly_return NUMERIC(10,6) NOT NULL,
  rank INTEGER NOT NULL,
  is_latest BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One row per user per week (enables idempotent inserts)
CREATE UNIQUE INDEX weekly_leaderboard_user_week
ON public.weekly_leaderboard (user_id, week_start);

-- Fast current leaderboard lookups
CREATE INDEX weekly_leaderboard_latest_rank
ON public.weekly_leaderboard (is_latest, rank);

-- Frontend view: current leaderboard
CREATE VIEW weekly_leaderboard_current AS
SELECT * FROM weekly_leaderboard
WHERE is_latest = true
ORDER BY rank;

-- Frontend view: positive performers only (future use)
CREATE VIEW weekly_leaderboard_current_positive AS
SELECT * FROM weekly_leaderboard
WHERE is_latest = true AND weekly_return > 0
ORDER BY weekly_return DESC;
